name: Diff Check
on:
 push:
   branches:
     - main

jobs:
 compare:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Get Diff
       run: |
         diff -u <(sort users_1.yml) <(sort users_2.yml) > diff.txt
         if [ -s diff.txt ]; then
           cat diff.txt | grep -vE "^[\ \<\>]*$"
           exit 1
         fi
